#!/usr/bin/env python3
"""Download and cache a processed OSM graph for a supported city."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1] / "backend"
sys.path.insert(0, str(BACKEND_ROOT))

from app.config import settings  # noqa: E402
from app.graph.loader import build_city_graph  # noqa: E402
from app.graph.registry import CITY_REGISTRY  # noqa: E402
from app.graph.store import processed_graph_paths, read_graph_metadata  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "city_id",
        choices=sorted(CITY_REGISTRY.keys()),
        help="City identifier to build",
    )
    args = parser.parse_args()

    if CITY_REGISTRY[args.city_id].is_fixture:
        print(
            "The fixture graph is generated by tests; nothing to build.",
            file=sys.stderr,
        )
        return 1

    graph = build_city_graph(args.city_id)
    paths = processed_graph_paths(settings.processed_data_dir, args.city_id)
    metadata = read_graph_metadata(paths)

    print(f"Built graph for {args.city_id}")
    print(f"  graphml: {paths.graphml}")
    print(f"  pickle:  {paths.pickle}")
    print(f"  nodes:   {graph.number_of_nodes()}")
    print(f"  edges:   {graph.number_of_edges()}")
    print(f"  version: {metadata['graphVersion']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
